apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-config
data:
  PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-service.default.svc.cluster.local:27017/local?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.6"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: nareshkaushik36/user-api:0.1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: user-api-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: user-api-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /api/users/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: user-api-service
              port:
                number: 80
